/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.bo.gastoBo;
import proyecto.clases.Gasto;

public class Registrogastos extends javax.swing.JFrame {

    gastoBo gbo = new gastoBo();
    private Object mensaje;

    LocalDate fecha = LocalDate.now();
    DateTimeFormatter formateado = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    String fechaTexto = fecha.format(formateado);

    public Registrogastos() {
        initComponents();
        setLocationRelativeTo(null);;
        listarGasto();
        txtidgasto.setEditable(false);
        txtfecha.setText(fechaTexto);
        txtrazon.setEditable(false);
    }

    public void listarGasto() {
        gbo.listarGastos(tbgastos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnregresar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadescripcion = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        txtrazon = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtidgasto = new javax.swing.JTextField();
        btnagregargasto = new javax.swing.JButton();
        btnlimpiargasto = new javax.swing.JButton();
        btnmodificargasto = new javax.swing.JButton();
        btneliminargasto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbgastos = new javax.swing.JTable();
        btnmercancia = new javax.swing.JButton();
        btntransporte = new javax.swing.JButton();
        btngastosoperativos = new javax.swing.JButton();
        btnreparaciones = new javax.swing.JButton();
        btnsalarios = new javax.swing.JButton();
        btnotros = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtbuscargasto = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-hacia-atrasnegro 32px.png"))); // NOI18N
        btnregresar.setBorderPainted(false);
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel22.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("Razón:");

        txtadescripcion.setColumns(20);
        txtadescripcion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtadescripcion.setForeground(new java.awt.Color(43, 42, 42));
        txtadescripcion.setLineWrap(true);
        txtadescripcion.setRows(5);
        txtadescripcion.setWrapStyleWord(true);
        txtadescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(txtadescripcion);

        jLabel23.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel23.setText("Descripción:");

        jLabel24.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel24.setText("Monto:");

        txtmonto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtmonto.setForeground(new java.awt.Color(43, 42, 42));

        txtrazon.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtrazon.setForeground(new java.awt.Color(43, 42, 42));

        jLabel25.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel25.setText("Fecha:");

        txtfecha.setEditable(false);
        txtfecha.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(43, 42, 42));

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel27.setText("S/.");

        jLabel28.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel28.setText("Id:");

        txtidgasto.setEditable(false);
        txtidgasto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtidgasto.setForeground(new java.awt.Color(43, 42, 42));
        txtidgasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidgastoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtidgasto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrazon)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidgasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        btnagregargasto.setBackground(new java.awt.Color(248, 126, 44));
        btnagregargasto.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        btnagregargasto.setForeground(new java.awt.Color(255, 255, 255));
        btnagregargasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar 24px.png"))); // NOI18N
        btnagregargasto.setText("Agregar");
        btnagregargasto.setBorder(null);
        btnagregargasto.setBorderPainted(false);
        btnagregargasto.setFocusable(false);
        btnagregargasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregargastoActionPerformed(evt);
            }
        });

        btnlimpiargasto.setBackground(new java.awt.Color(248, 126, 44));
        btnlimpiargasto.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        btnlimpiargasto.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiargasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpieza-de-datos 32px.png"))); // NOI18N
        btnlimpiargasto.setText("Limpiar");
        btnlimpiargasto.setBorder(null);
        btnlimpiargasto.setBorderPainted(false);
        btnlimpiargasto.setFocusable(false);
        btnlimpiargasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiargastoActionPerformed(evt);
            }
        });

        btnmodificargasto.setBackground(new java.awt.Color(248, 126, 44));
        btnmodificargasto.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        btnmodificargasto.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificargasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar 32px.png"))); // NOI18N
        btnmodificargasto.setText("Modificar");
        btnmodificargasto.setBorder(null);
        btnmodificargasto.setBorderPainted(false);
        btnmodificargasto.setFocusable(false);
        btnmodificargasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificargastoActionPerformed(evt);
            }
        });

        btneliminargasto.setBackground(new java.awt.Color(248, 126, 44));
        btneliminargasto.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        btneliminargasto.setForeground(new java.awt.Color(255, 255, 255));
        btneliminargasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar 32px.png"))); // NOI18N
        btneliminargasto.setText("Eliminar");
        btneliminargasto.setBorder(null);
        btneliminargasto.setBorderPainted(false);
        btneliminargasto.setFocusable(false);
        btneliminargasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminargastoActionPerformed(evt);
            }
        });

        tbgastos.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        tbgastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbgastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbgastosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbgastos);

        btnmercancia.setBackground(new java.awt.Color(243, 243, 243));
        btnmercancia.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnmercancia.setForeground(new java.awt.Color(74, 100, 125));
        btnmercancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comida (1).png"))); // NOI18N
        btnmercancia.setText("Compra de mercancía");
        btnmercancia.setToolTipText("Compra de mercancía");
        btnmercancia.setActionCommand("");
        btnmercancia.setFocusable(false);
        btnmercancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmercanciaActionPerformed(evt);
            }
        });

        btntransporte.setBackground(new java.awt.Color(243, 243, 243));
        btntransporte.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btntransporte.setForeground(new java.awt.Color(74, 100, 125));
        btntransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/autobus.png"))); // NOI18N
        btntransporte.setText("Transporte");
        btntransporte.setFocusable(false);
        btntransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransporteActionPerformed(evt);
            }
        });

        btngastosoperativos.setBackground(new java.awt.Color(243, 243, 243));
        btngastosoperativos.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btngastosoperativos.setForeground(new java.awt.Color(74, 100, 125));
        btngastosoperativos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grifo-de-agua.png"))); // NOI18N
        btngastosoperativos.setText("Gastos operativos");
        btngastosoperativos.setFocusable(false);
        btngastosoperativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngastosoperativosActionPerformed(evt);
            }
        });

        btnreparaciones.setBackground(new java.awt.Color(243, 243, 243));
        btnreparaciones.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnreparaciones.setForeground(new java.awt.Color(74, 100, 125));
        btnreparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/herramientas-para-reparar.png"))); // NOI18N
        btnreparaciones.setText("Reparaciones menores");
        btnreparaciones.setFocusable(false);
        btnreparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreparacionesActionPerformed(evt);
            }
        });

        btnsalarios.setBackground(new java.awt.Color(243, 243, 243));
        btnsalarios.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnsalarios.setForeground(new java.awt.Color(74, 100, 125));
        btnsalarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salario.png"))); // NOI18N
        btnsalarios.setText("Salarios");
        btnsalarios.setFocusable(false);
        btnsalarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalariosActionPerformed(evt);
            }
        });

        btnotros.setBackground(new java.awt.Color(243, 243, 243));
        btnotros.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnotros.setForeground(new java.awt.Color(74, 100, 125));
        btnotros.setText("Otros gastos");
        btnotros.setFocusable(false);
        btnotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnotrosActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupita.png"))); // NOI18N

        txtbuscargasto.setBackground(new java.awt.Color(255, 204, 204));
        txtbuscargasto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtbuscargasto.setForeground(new java.awt.Color(51, 51, 51));
        txtbuscargasto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtbuscargasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscargastoActionPerformed(evt);
            }
        });
        txtbuscargasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscargastoKeyPressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 102, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel26.setText("Seleccione una:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gastos");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/billetera.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(230, 230, 230))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtbuscargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(388, 388, 388))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(146, 146, 146)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnmercancia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnreparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btntransporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btngastosoperativos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnsalarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnotros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(61, 61, 61)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnlimpiargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnagregargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnmodificargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btneliminargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnmercancia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btntransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btngastosoperativos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnreparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnsalarios, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnotros, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnagregargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnlimpiargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnmodificargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btneliminargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbuscargasto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        PrincipalAdmin fv = new PrincipalAdmin();
        fv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnagregargastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregargastoActionPerformed
        if (txtrazon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene los campos vacios");
        } else {
            Gasto g = new Gasto();
            LocalDate fechaActual = LocalDate.now();
            g.setFecha(fechaActual);
            g.setRazon(txtrazon.getText());
            g.setDescripcion(txtadescripcion.getText());
            g.setMonto(txtmonto.getText());
            gbo.agregarGasto(g);
        }
        JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
        listarGasto();
    }//GEN-LAST:event_btnagregargastoActionPerformed

    private void btnlimpiargastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiargastoActionPerformed
        limpiarGastos();
    }//GEN-LAST:event_btnlimpiargastoActionPerformed

    private void btnmodificargastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificargastoActionPerformed
        if (txtrazon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene los campos vacíos");
        } else {
            Gasto g = new Gasto();
            g.setId(Integer.parseInt(txtidgasto.getText()));
            g.setRazon(txtrazon.getText());
            g.setDescripcion(txtadescripcion.getText());
            g.setMonto(txtmonto.getText());

            String mensaje = gbo.modificarGasto(g);

            if (mensaje.equals("Actualizado correctamente")) {
                JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
                listarGasto();
            } else {
                JOptionPane.showMessageDialog(null, mensaje);
            }
        }
    }//GEN-LAST:event_btnmodificargastoActionPerformed

    private void btneliminargastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminargastoActionPerformed
        int selectedRow = tbgastos.getSelectedRow();
        String idGastoStr = (String) tbgastos.getValueAt(selectedRow, 0);
        int idGasto = Integer.parseInt(idGastoStr);
        String mensaje = gbo.eliminarGasto(idGasto);
        JOptionPane.showMessageDialog(null, mensaje);
        listarGasto();
    }//GEN-LAST:event_btneliminargastoActionPerformed

    private void txtbuscargastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscargastoActionPerformed
        buscarGastos();
    }//GEN-LAST:event_txtbuscargastoActionPerformed

    private void txtbuscargastoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscargastoKeyPressed

    }//GEN-LAST:event_txtbuscargastoKeyPressed

    private void btnotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnotrosActionPerformed
        txtrazon.setText("");
        txtrazon.setEditable(true);
        txtrazon.requestFocus();
    }//GEN-LAST:event_btnotrosActionPerformed

    private void btnmercanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmercanciaActionPerformed
        txtrazon.setText("");
        txtrazon.setText("Compra de mercancía");
        txtrazon.setEditable(false);
    }//GEN-LAST:event_btnmercanciaActionPerformed

    private void btntransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransporteActionPerformed
        txtrazon.setText("");
        txtrazon.setText("Transporte");
        txtrazon.setEditable(false);
    }//GEN-LAST:event_btntransporteActionPerformed

    private void btngastosoperativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngastosoperativosActionPerformed
        txtrazon.setText("");
        txtrazon.setText("Gastos operativos");
        txtrazon.setEditable(false);
    }//GEN-LAST:event_btngastosoperativosActionPerformed

    private void btnreparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreparacionesActionPerformed
        txtrazon.setText("");
        txtrazon.setText("Reparaciones menores");
        txtrazon.setEditable(false);
    }//GEN-LAST:event_btnreparacionesActionPerformed

    private void btnsalariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalariosActionPerformed
        txtrazon.setText("");
        txtrazon.setText("Salarios");
        txtrazon.setEditable(false);
    }//GEN-LAST:event_btnsalariosActionPerformed

    private void tbgastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbgastosMouseClicked
        int seleccion = tbgastos.rowAtPoint(evt.getPoint());
        txtidgasto.setText(tbgastos.getValueAt(seleccion, 0) + "");
        txtfecha.setText(tbgastos.getValueAt(seleccion, 1) + "");
        txtrazon.setText(tbgastos.getValueAt(seleccion, 2) + "");
        txtadescripcion.setText(tbgastos.getValueAt(seleccion, 3) + "");
        txtmonto.setText(tbgastos.getValueAt(seleccion, 4) + "");
    }//GEN-LAST:event_tbgastosMouseClicked

    private void txtidgastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidgastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidgastoActionPerformed

    private void limpiarGastos() {
        txtidgasto.setText("");
        txtrazon.setText("");
        txtadescripcion.setText("");
        txtmonto.setText("");
        txtbuscargasto.setText("");
        btnmercancia.requestFocus();
    }

    private void buscarGastos() {
        String dato = txtbuscargasto.getText().trim();
        DefaultTableModel tabla = (DefaultTableModel) tbgastos.getModel();
        gbo.buscarGasto(dato, tabla);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrogastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrogastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrogastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrogastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrogastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregargasto;
    private javax.swing.JButton btneliminargasto;
    private javax.swing.JButton btngastosoperativos;
    private javax.swing.JButton btnlimpiargasto;
    private javax.swing.JButton btnmercancia;
    private javax.swing.JButton btnmodificargasto;
    private javax.swing.JButton btnotros;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnreparaciones;
    private javax.swing.JButton btnsalarios;
    private javax.swing.JButton btntransporte;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbgastos;
    private javax.swing.JTextArea txtadescripcion;
    private javax.swing.JTextField txtbuscargasto;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtidgasto;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtrazon;
    // End of variables declaration//GEN-END:variables
}
